appName: "Server Monitoring"

onDemandCollectors:
  - klass: "loader.monitor.collector.DFCollector"
    name: "df"
    requiredParams: []
  - klass: "loader.monitor.collector.jmx.JMXCollector"
    name: "jmx"
    requiredParams: ["host","port"]
  - klass: "loader.monitor.collector.MysqlConnectionCollector"
    name: "dbConnections"
    requiredParams: ["host","port","user","password","db"]
  - klass: "loader.monitor.collector.SocketCheckCollector"
    name: "socketCheck"
    requiredParams: ["host","port"]

http:
  port: 7777
  adminPort: 7771
  rootPath: "/monitoring-service/*"

logging:
  level: INFO
