appName: "Loader Agent"

serverInfo:
  host: "localhost"
  port: 9999

registrationParams:
  env: "corp"

libStorageConfig:
  libPath: "/usr/share/loader-agent/libs"
  platformLibPath: "/usr/share/loader-agent/platformLibs"
  mappingFile: "/usr/share/loader-agent/config/mapping.properties"

jobProcessorConfig:
  maxJobs: 1
  jobCLIFormat: "java -Xms500m -Xmx2g -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port={jmxPort} -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -cp {classpath} com.open.perf.main.Main -f {jobJson} -j {jobId} -s /var/log/loader-agent/jobs/ > /var/log/loader-agent/jobs/{jobId}/log"
  pendingJobCheckInterval: 5000
  healthCheckInterval: 10000
  memoryUsageThreshold: 80
  cpuUsageThreshold: 80

jobFSConfig:
  jobBasePath: "/var/log/loader-agent/jobs"
  jobPath: "/var/log/loader-agent/jobs/{jobId}"
  jobFile: "/var/log/loader-agent/jobs/{jobId}/job.json"
  jobLogFile: "/var/log/loader-agent/jobs/{jobId}/log"
  runningJobsFile: "/var/log/loader-agent/jobs/runningJobs"

jobStatSyncConfig:
  syncInterval: 10000
  #Lines Per File
  linesToSyncInOneGo: 150000
  #Keep Lines Read keeping "15000 Lines per second to push to server" in mind
  # So if sync interval is 15000, linesToSyncInOneGo should be 15000 * 10  = 150000

http:
  port: 8888
  adminPort: 8881
  rootPath: "/loader-agent/*"

logging:

  level: INFO

  # Settings for logging to stdout.
  console:

      # If true, write log statements to stdout.
    enabled: true

      # Do not display log statements below this threshold to stdout.
    threshold: ALL